[package]
name = "sqlite-provider"
version = "0.1.0"
authors = ["Prabir Shrestha <mail@prabir.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
objstor = { path = "../objstor" }
async-trait = "0.1.50"
